### ISSUE TITLE
Bug in css preprocesors: module css, autoprefix

### ISSUE THREAD

**Issue by FDiskas** [remoteinterview/zero#36]
I followed `parcel` documentation https://parceljs.org/css.html#postcss and it worked ok, but with `zero` it does not works.
[demo.zip](https://github.com/remoteinterview/zero/files/2949738/demo.zip)

**Comment by asadm** [comment]
Can you move `package.json` into `src` and then run `zero` *inside* src directory. When you do `zero src` the `package.json` isn't considered at all since it's not inside `src` directory. Hope that makes sense.

**Comment by FDiskas** [comment]
Tried but nothing changed.
parcel generates:
```css
body {
  font-family: sans-serif;
  font-size: 12px;
  padding: 12px;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none; }

._button_00649 {
  border: 1px solid red; }


/*# sourceMappingURL=/app.c328ef1a.css.map */
```
zero generates:
```css
body {
  font-family: sans-serif;
  font-size: 12px;
  padding: 12px;
  user-select: none; }

.button {
  border: 1px solid red; }


/*# sourceMappingURL=/zero-builds/da39a3ee5e6b4b0d3255bfef95601890afd80709/html.static/app.c328ef1a.css.map */
```

Here is demo project: :mag_right:
[Demo-app.zip](https://github.com/remoteinterview/zero/files/2954102/Demo-app.zip)
