### ISSUE TITLE
Feature Request: scss, sass & stylus files

### ISSUE THREAD

**Issue by JohnDeved** [remoteinterview/zero#51]
hey, it would be awesome if we could write a scss / stylus files standalone.
my proposal is to be able to write a file like this:

**./mystyle.styl**
```styl
html
    background red
```

and get this back from zero:
**localhost:3000/mystyle.css**
```css
html {
  background: #f00;
}
```
**localhost:3000/mystyle.min.css**
```css
html{background:red}
```
